import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'benchmarks',
    {
      type: 'category',
      label: 'API',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;