name: release
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: nearform-actions/optic-release-automation-action@v4
        with:
          publish-mode: oidc
          semver: ${{ github.event.inputs.semver }}
          build-command: |
            npm install
